source/api/urls.py
from django.urls import path
from api.views import IssueDetailAPIView, DeleteView, UpdateView


urlpatterns = [
    path('projects/detail/<int:pk>', IssueDetailAPIView.as_view()),
    path('projects/update/<int:pk>', UpdateView.as_view()),
    path('projects/delete/<int:pk>', DeleteView.as_view())
]

source/issuetracker/urls.py
from django.urls import path
from issuetracker.views.base import IndexView
from issuetracker.views.issues import IssueView, IssueAddView, IssueUpdateView, IssueDelView, IssueDelConfirmView
from issuetracker.views.projects import ProjectsView, ProjectView, ProjectAddView, UserAddView
from issuetracker.views.example import echo, get_token, json_issues


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('issue/<int:pk>', IssueView.as_view(), name='issue'),
    path('issue_add/', IssueAddView.as_view(), name='issue_add'),
    path('issue_update/<int:pk>', IssueUpdateView.as_view(), name='issue_update'),
    path('issue_del/<int:pk>', IssueDelView.as_view(), name='issue_del'),
    path('issue_del_confirm/<int:pk>', IssueDelConfirmView.as_view(), name='del_confirm'),
    path('projects/', ProjectsView.as_view(), name='projects'),
    path('project/<int:pk>', ProjectView.as_view(), name='project'),
    path('project_add/', ProjectAddView.as_view(), name='project_add'),
    path('project/<int:pk>/user_add/', UserAddView.as_view(), name='add_user'),
    path('echo/', echo, name='echo'),
    path('token/', get_token, name='token'),
    path('json_issues/', json_issues, name='json_issues')
]

source/webproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from api.views import IssueAPIView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('issuetracker.urls')),
    path('auth/', include('accounts.urls')),
    path('api/', include('api.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

source/issuetracker/models.py
from django.db import models


class StatusIssue(models.Model):
    title = models.CharField(
        verbose_name='Название',
        max_length=20,
        null=False,
        blank=False
    )

    def __str__(self) -> str:
        return f'{self.title}'


class TypeIssue(models.Model):
    title = models.CharField(
        verbose_name='Название',
        max_length=20,
        null=False,
        blank=False
    )

    def __str__(self) -> str:
        return f'{self.title}'


class Issue(models.Model):
    title = models.CharField(
        verbose_name='Краткое описание',
        max_length=100,
        null=False,
        blank=False
    )
    description = models.TextField(
        verbose_name='Полное описание',
        max_length=800,
        default=''
    )
    status = models.ForeignKey(
        to='issuetracker.StatusIssue',
        related_name='statuses',
        on_delete=models.RESTRICT,
        verbose_name='Статус'
    )
    type_issue = models.ManyToManyField(
        to='issuetracker.TypeIssue',
        related_name='issues',
        verbose_name='Тип',
        blank=True
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Время создания',
    )
    updateted_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Время обновления'
    )

    def __str__(self) -> str:
        return f'{self.title}'

source/issuetracker/models/issues.py
from django.db import models



class Issue(models.Model):
    title = models.CharField(
        verbose_name='Краткое описание',
        max_length=100,
        null=False,
        blank=False
    )
    description = models.TextField(
        verbose_name='Полное описание',
        max_length=800,
        default=''
    )
    status = models.ForeignKey(
        to='issuetracker.StatusIssue',
        related_name='issues',
        on_delete=models.RESTRICT,
        verbose_name='Статус',
        default='New'
    )
    type_issue = models.ManyToManyField(
        to='issuetracker.TypeIssue',
        related_name='issues',
        verbose_name='Тип',
        blank=True,
        default='Task'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Время создания',
    )
    updateted_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Время обновления'
    )
    project = models.ForeignKey(
        to='issuetracker.Project',
        related_name='issues',
        on_delete=models.CASCADE,
        verbose_name='Проект',
        default=1
    )

    def __str__(self) -> str:
        return f'{self.title}'

source/issuetracker/models/projects.py
from tokenize import blank_re
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    title = models.CharField(
        verbose_name='Название',
        max_length=100,
        null=False,
        blank=False
    )
    description = models.TextField(
        verbose_name='Описание',
        max_length=800,
        null=False,
        blank=True,
        default=''
    )
    date_begin = models.DateField(
        verbose_name='Дата начала',
        max_length=10,
        null=False,
        blank=False
    )
    date_end = models.DateField(
        verbose_name='Дата окончания',
        max_length=10,
        default='',
        null=True,
        blank=True
    )
    user = models.ManyToManyField(
        to=User,
        related_name='projects',
        verbose_name = 'Пользователь',
        blank=True
    )


    def __str__(self):
        return f'{self.title}'

source/issuetracker/models/statuses.py
from django.db import models


class StatusIssue(models.Model):
    title = models.CharField(
        verbose_name='Название',
        max_length=20,
        null=False,
        blank=False
    )

    def __str__(self) -> str:
        return f'{self.title}'

source/issuetracker/models/types_issue.py
from django.db import models


class TypeIssue(models.Model):
    title = models.CharField(
        verbose_name='Название',
        max_length=20,
        null=False,
        blank=False
    )

    def __str__(self) -> str:
        return f'{self.title}'

source/issuetracker/forms.py
from django import forms
from django.forms import ValidationError
from issuetracker.models.issues import Issue
from issuetracker.models.projects import Project
from django.core.validators import MinLengthValidator, BaseValidator
from django.contrib.auth.models import User



def max_length_validator(string):
    if len(string) > 15:
        raise ValidationError("Максимальная длина строки 15 символов")
    return string


class CustomLengthValidator(BaseValidator):
    def __init__(self, limit_value=20, message=''):
        super(CustomLengthValidator, self).__init__(limit_value=limit_value, message=message)

    def compare(self, value, max_value):
        return max_value < value

    def clean(self, value):
        return len(value)

       

        

class IssueForm(forms.ModelForm):
    title = forms.CharField(
        label='Заголовок',
        validators=(
            MinLengthValidator(limit_value=2), 
            CustomLengthValidator(),
            ),
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Issue
        fields = ('title', 'description', 'status', 'type_issue', 'project')
        widgets = {
            'description': forms.Textarea(attrs={'class': 'form-control', 'style': 'height:150px'}),
            'status': forms.RadioSelect,
            'type_issue': forms.CheckboxSelectMultiple
        }

    def clean_title(self):
        title = self.cleaned_data.get('title')
        if Issue.objects.filter(title=title).exists():
            raise ValidationError('Заголовок с таким названием уже существует')
        return title


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('title', 'description', 'date_begin', 'date_end')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'style': 'height:150px'}),
            'date_begin': forms.TextInput(attrs={'class': 'form-control', 'type': 'date'}),
            'date_end': forms.TextInput(attrs={'class': 'form-control', 'type': 'date'})
        }


class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label='Найти')


class AddUserForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('user',)
        widgets = {'user': forms.CheckboxSelectMultiple}

source/issuetracker/views/base.py
from django.views.generic import ListView
from issuetracker.models.issues import Issue
from issuetracker.forms import SearchForm
from django.db.models import Q
from urllib.parse import urlencode



class IndexView(ListView):
    template_name = 'index.html'
    model = Issue
    context_object_name = 'issues'
    ordering = ('-created_at',)
    paginate_by = 10


    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get('search')
        return None

    def get_queryset(self):
        queryset = super(IndexView, self).get_queryset()
        if self.search_value:
            query = Q(title__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_context_data(self, object_list=None, **kwargs):
        context = super(IndexView, self).get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

source/issuetracker/views/example.py
import json
from datetime import datetime
from django.http import HttpResponse, HttpResponseNotAllowed, JsonResponse
from django.views.decorators.csrf import ensure_csrf_cookie
from issuetracker.models.issues import Issue

def echo(request, *args, **kwargs):
    answer = {
        'time': datetime.now().strftime('%Y-%m-%d %h: %M: %S'),
        'method': request.method
    }
    if request.body:
        answer['answer'] = json.loads(request.body)
    return JsonResponse(answer)

@ensure_csrf_cookie
def get_token(request, *args, **kwargs):
    if request.method == 'GET':
        return HttpResponse()
    return HttpResponseNotAllowed(f'Not allowed {request.method}')


def json_issues(request, *args, **kwargs):
    if request.method == 'GET':
        fields = ('pk', 'title', 'description', 'status', 'type_issue')
        issues = Issue.objects.values(*fields)
        return JsonResponse(list(issues), safe=False)
    if request.method == 'POST' and request.body:
        issue = json.loads(request.body)
        try:
            response_data = Issue.objects.create(**issue)
            response = JsonResponse({"id"})
            response.status_code = 201
        except Exception as e:
            print(e)
            raise
            response_data = {"detail": "Неккоректный набор полей"}
            response = JsonResponse(response_data)
            response.status_code = 400
        return response

source/issuetracker/views/issues.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, View
from issuetracker.models.issues import Issue
from issuetracker.forms import IssueForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


class CustomUserPassesTestMixin(UserPassesTestMixin):
    groups = []

    def test_func(self):
        return self.request.user.groups.filter(name__in=self.groups).exists()



class IssueView(DetailView):
    template_name = 'issue.html'
    model = Issue



class IssueAddView(CustomUserPassesTestMixin, LoginRequiredMixin, CreateView):
    template_name = 'issue_add.html'
    form_class = IssueForm
    model = Issue
    groups = ['manager', 'lead', 'dev']
    

    def get_success_url(self):
        return reverse('issue', kwargs={'pk': self.object.pk})


class IssueUpdateView(CustomUserPassesTestMixin, LoginRequiredMixin, UpdateView):
    template_name = 'issue_update.html'
    form_class = IssueForm
    model = Issue
    pk_url_kwarg = 'pk'
    context_object_name = 'issue'
    groups = ['manager', 'lead', 'dev']
    
    def get_success_url(self):
        return reverse('project', kwargs={'pk': self.object.pk})



class IssueDelView(CustomUserPassesTestMixin, LoginRequiredMixin, DeleteView):
    template_name = 'issue_del.html'
    model = Issue
    success_url = reverse_lazy('index')
    groups = ['manager', 'lead']



class IssueDelConfirmView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        issue = get_object_or_404(Issue, pk=kwargs['pk'])
        issue.delete()
        return redirect('index')

source/issuetracker/views/projects.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, CreateView, ListView, UpdateView
from issuetracker.models.issues import Issue
from issuetracker.forms import ProjectForm, AddUserForm
from issuetracker.models.projects import Project
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


class CustomUserPassesTestMixin(UserPassesTestMixin):
    groups = []

    def test_func(self):
        return self.request.user.groups.filter(name__in=self.groups).exists()

class ProjectsView(ListView):
    template_name = 'projects.html'
    model = Project
    context_object_name = 'projects'


class ProjectView(DetailView):
    template_name = 'project.html'
    model = Project
 
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project = self.object
        context['issues'] = Issue.objects.filter(project=project)
        return context
    

class ProjectAddView(CustomUserPassesTestMixin, LoginRequiredMixin, CreateView):
    template_name = 'project_add.html'
    form_class = ProjectForm
    model = Project
    groups = ['manager']

    def get_success_url(self):
        return reverse('project', kwargs={'pk': self.object.pk})


class UserAddView(CustomUserPassesTestMixin, LoginRequiredMixin, UpdateView):
    template_name = 'add_user.html'
    form_class = AddUserForm
    model = Project
    pk_url_kwarg = 'pk'
    context_object_name = 'my_users'
    groups = ['manager', 'lead']

    def get_success_url(self):
        return reverse('project', kwargs={'pk': self.object.pk})
    

source/issuetracker/templates/add_user.html
{% extends 'base.html' %}

{% block title %}
    Add user
{% endblock %}

{% block content %}
<h1 class="m-3">Добавление пользователя или удаление пользователя: </h1>
<form class="m-3" action="" method="POST">
    {% csrf_token %}
    <div class="ms-3 mt-3">
        {{ form }}
    </div>
    {% for error in form.errors %}
    <div class="ms-2 text-danger">{{ error }}</div>
    {% endfor %}
    <button type="submit" class="btn btn-primary ms-2 ps-3 pe-3 mt-4">Сохранить</button>
</form>
<p class="mt-4 ms-2"><a href="">вернуться к проекту</a></p>
{% endblock %}

source/issuetracker/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %} Home {% endblock %}
  </title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body class="bg-secondary bg-opacity-10">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark m-0">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}"><h1>IssueTracker</h1></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon text-light"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          {% block menu %}
          {% endblock %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              проекты
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'projects' %}">все проекты</a></li>
            {% if user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'project_add' %}">создать проект</a></li>
            {% endif %}
          </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              задачи
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'index' %}">все задачи</a></li>
            {% if user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'issue_add' %}">создать задачу</a></li>
            {% endif %}
          </ul>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item text-white">
            <p class="pt-2 ms-3">Здравствуйте, {{ user.username }}!</p> 
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Выход</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Вход</a> }
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}">Регистрация</a> }
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    {% block content %}
    {% endblock %}  
  </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</html>

source/issuetracker/templates/index.html
{% extends 'base.html' %}

{% block menu %}
{% endblock %}

{% block content %}
<div style="text-align: center;" class="title mt-3 mb-3">
  <h2>Список задач:</h2>
  {% include 'partial/search.html' %}
</div>
<div class="row">
{% for issue in issues %}
<div class="col-md-12 col-xl-6 mb-4">
  <div class="card p-3 m-2">
    <div class="card-header p-0 bg-white">
      <p><a class="text-dark" style="text-decoration: none;" href="{% url 'issue' issue.pk %}"><h5 class="card-title">{{issue.title}}</h5></a></p>
    </div>
    <p class="ms-2">Проект: {{ issue.project }}</p>
    Тип: 
    <p class="ms-2">
    {% for type in issue.type_issue.all %}
    <strong>{{ type }}</strong><br>
    {% endfor %}
    </p>
    <p>Статус: <strong>{{ issue.status }}</strong></p>
    <p><strong><a href="{% url 'issue' issue.pk %}" class="btn btn-primary ps-5 pe-5">Подробнее</a></strong></p>
    {% if user.is_authenticated %}
    <p style="text-align: right;"></p>
    {% if perms.issuetracker.change_issue  %}
    <a  class="link-success" href="{% url 'issue_update' issue.pk %}">редактировать</a> 
    {% endif %}
    {% if perms.issuetracker.delete_issue  %}
      <a class="link-danger" href="{% url 'issue_del' issue.pk %}">удалить</a>
      {% endif %}
    </p>
    {% endif %}
  </div>
</div>
{% empty %}
<p>Задачи не найдены!</p>
{% endfor %}
    {% if is_paginated %}
      {% include 'partial/pagination.html' %}
    {% endif %}


</div><br>
{% endblock %}

source/issuetracker/templates/issue.html
{% extends 'base.html' %}

{% block title %}
    Task - {{ issue.title }}
{% endblock %}


{% block content %}
<div class="card mb-3 mt-4">
    <div class="card-body">
        <h4 class="card-title">{{ issue.title }}</h4>
        Тип:
        
        <p class="card-text">
            {% for type in issue.type_issue.all %}
            <strong class="ms-2">{{type}}</strong><br>
            {% endfor %}
        </p>
        <p class="card-text">Статус: <strong >{{issue.status}}</strong></p>
        <p class="card-text">{{ issue.description | linebreaks }}</p>
        <p style="text-align: right;"><small><a  class="link-success" href="">редактировать</a> | <a class="link-danger" href="">удалить</a></small></p>
    </div>
</div>
<p class="mt-4 ms-2"><a href="{% url 'index' %}">вернуться на главную</a></p>
{% endblock %}

source/issuetracker/templates/issue_add.html
{% extends 'base.html' %}

{% block title %}
    Issue create
{% endblock %}


{% block content %}
<h1 class="m-3">Создание новой задачи: </h1>
<form class="m-3" action="{% url 'issue_add' %}" method="POST">
    {% include 'partial/issue_form.html' with button_text='Создать' %}
</form>
<p class="mt-4 ms-2"><a href="{% url 'index' %}">вернуться на главную</a></p>
{% endblock %}

source/issuetracker/templates/issue_del.html
{% extends 'base.html' %}

{% block title %}
    Issue delete
{% endblock %}



{% block content %}
<div class="card mb-3 mt-4">
    <div class="card-body">
      <h2 class="m-5">Вы точно хотите удалить запись "{{ issue.title }}"?</h2>  
      <form action="{% url 'del_confirm' issue.pk %}" method="post">
        {% csrf_token %}
        <p style="text-align: center;">
            <button type="submit" class="btn btn-danger ms-2 p-3 mt-4">Удалить</button>
            <a href="{% url 'index' %}" class="btn btn-success ms-2 mt-4 p-3">Отменить</a>
        </p> 
      </form>
    </div>
</div>
{% endblock %}

source/issuetracker/templates/issue_update.html
{%  extends 'base.html '%}

{% block title %}
    Issue {{ issue.title }} edit
{% endblock %}


{% block content %}
<h1 class="m-3">Редактирование задачи: </h1>
<form class="m-3" action="" method="POST">
    {% include 'partial/issue_form.html' with button_text='Сохранить' %}
</form>
<p class="mt-4 ms-2"><a href="{% url 'index' %}">вернуться на главную</a></p>
{% endblock %}

source/issuetracker/templates/project.html
{% extends 'base.html' %}

{% block title %}
    Project - {{ project.title }}
{% endblock %}

{% block content %}
<div class="card mb-3 mt-4">
    <div class="card-body">
        <h4 class="card-title">{{ project.title }}</h4>
        <p class="card-text">{{ project.description | linebreaks }}</p>
        <p class="card-text">Начало: <strong >{{project.date_begin}}</strong></p>
        <p class="card-text">Конец: <strong >{{project.date_begin}}</strong></p>
        <p>Пользователи:</p>
        {% if project.user.all %}
        {% for user in project.user.all %}
          {{ user.username }}, 
        {% endfor %}
        {% else %}
          <p>Пользователей нет</p>
        {% endif %}
        <p><a href="{% url 'add_user' project.pk %}">Добавить нового пользователя</a></p>
       
    </div>
</div>
<div class="row">
    {% for issue in issues %}
    <div class="col-md-12 col-xl-4 mb-4">
      <div class="card p-3 m-2">
        <div class="card-header p-0 bg-white">
          <p><a class="text-dark" style="text-decoration: none;" href="{% url 'issue' issue.pk %}"><h5 class="card-title">{{issue.title}}</h5></a></p>
        </div>
        <p class="ms-2">Проект: {{ issue.project }}</p>
        Тип: 
        <p class="ms-2">
        {% for type in issue.type_issue.all %}
        <strong>{{ type }}</strong><br>
        {% endfor %}
        </p>
        <p>Статус: <strong>{{ issue.status }}</strong></p>
        <p><strong><a href="{% url 'issue' issue.pk %}" class="btn btn-primary ps-5 pe-5">Подробнее</a></strong></p>
        <p style="text-align: right;"><small><a  class="link-success" href="{% url 'issue_update' issue.pk %}">редактировать</a> | <a class="link-danger" href="{% url 'issue_del' issue.pk %}">удалить</a></small></p>
      </div>
    </div>
    {% empty %}
    <p>Задачи не найдены!</p>
    {% endfor %}
        {% if is_paginated %}
          {% include 'partial/pagination.html' %}
        {% endif %}
    
    
    </div>

<p class="mt-4 ms-2"><a href="{% url 'index' %}">вернуться на главную</a></p>



{% endblock %}

source/issuetracker/templates/project_add.html
{% extends 'base.html' %}

{% block title %}
    Project create
{% endblock %}



{% block content %}
<h1 class="m-3">Создание нового проекта: </h1>
<form class="m-3" action="{% url 'project_add' %}" method="POST">
    {% include 'partial/project_form.html' with button_text='Создать' %}
</form>
<p class="mt-4 ms-2"><a href="{% url 'index' %}">вернуться на главную</a></p>
{% endblock %}

source/issuetracker/templates/project_issue_add.html
{% extends 'base.html' %}

{% block title %}
    Issue create
{% endblock %}

{% block content %}
<h1 class="m-3">Создание новой задачи: </h1>
<form class="m-3" action="{% url 'issue_add' %}" method="POST">
    {% include 'partial/project_issue_form.html' with button_text='Создать' %}
</form>
<p class="mt-4 ms-2"><a href="{% url 'index' %}">вернуться на главную</a></p>
{% endblock %}

source/issuetracker/templates/projects.html
{% extends 'base.html' %}

{% block title %}
    Projects
{% endblock %}

{% block content %}
<div style="text-align: center;" class="title mt-3 mb-3">
  <h2>Список проектов:</h2>
</div>
<div class="row">
{% for project in projects %}
<div class="col-md-12 col-xl-4 mb-4">
  <div class="card p-3 m-2">
    <div class="card-header p-0 bg-white">
      <p><a class="text-dark" style="text-decoration: none;" href="{% url 'project' project.pk %}"><h5 class="card-title">{{project.title}}</h5></a></p>
    </div>
    <p>Начало: <strong>{{ project.date_begin }}</strong></p>
    <p>Конец: <strong>{{ project.date_end }}</strong></p>
    <p><strong><a href="{% url 'project' project.pk %}" class="btn btn-primary ps-5 pe-5">Подробнее</a></strong></p>
  </div>
</div>
{% empty %}
<p>Проекты не найдены!</p>
{% endfor %}
    {% if is_paginated %}
      {% include 'partial/pagination.html' %}
    {% endif %}


</div>
{% endblock %}